nameOverride: ""
fullnameOverride: ""

app:
  name: sportnotifier
  replicaCount: 1
  image:
    repository: slezkin23/sportnotifier
    tag: ""
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  spring:
    profiles: local, datasource_h2

service:
  type: LoadBalancer
  protocol: TCP
  port: 8080
  targetPort: 80
