apiVersion: v1
kind: Service
metadata:
  name: {{ include "sportnotifier.fullname" . }}
  namespace: default
  labels:
    {{- include "sportnotifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sportnotifier.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
