apiVersion: v1
kind: Service
metadata:
  name: {{ include "sportnotifier.fullname" . }}
  namespace: default
  labels:
    {{- include "sportnotifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "sportnotifier.fullname" . }}
  ports:
    - protocol: TCP
      port: 8190
      targetPort: 8090
