server:
  port: ${PORT:8090}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:~/sportnotifier;MODE=postgresql;
  h2:
    console.enabled: true
  jpa:
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.lamardinho.sportnotifier.config.H2IdentifierNamingStrategy
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        globally-quoted-identifiers: true
  liquibase:
    enabled: off
  sql:
    init:
      data-locations:
        - classpath:sql/test.sql
  mail:
    #default-encoding: UTF-8
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_SERVER_USERNAME:secret}
    password: ${MAIL_SERVER_PASSWORD:secret}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    test-connection: false
    #cache:
    #type: simple

    #springdoc:
    # packagesToScan: com.example.sportnotifier
    #swagger-ui:
    # disable-swagger-default-url: true
  security:
    user:
      password: ${DEFAULT_PASSWORD:hello_world}

app:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN:secret}
      send-msg-post-url-template: ${TELEGRAM_SEND-MSG-POST-URL-TEMPLATE:https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s}
    chat-id:
      owner: ${OWNER_CHAT_ID:1}
  football-data-org:
    token: ${FOOTBALL_DATA_ORG_TOKEN:secret}
    scheduler:
      conditional: ${FOOTBALL_DATA_ORG_SCHEDULER_CONDITIONAL:false}
