server:
  port: ${PORT:8090}
spring:
  #datasource:
  #driver-class-name: org.postgresql.Driver
  #username: ${DB_USER:postgres}
  #password: ${DB_PASSWORD:}
  #url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:just_project}?currentSchema=public
  liquibase:
    enabled: off
    change-log: db/changelog/db-master.xml
  jpa:
    generate-ddl: false
    open-in-view: false
  mail:
    #default-encoding: UTF-8
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_SERVER_USERNAME:secret}
    password: ${MAIL_SERVER_PASSWORD:secret}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    test-connection: false
    #cache:
    #type: simple

    #springdoc:
    #packagesToScan: com.example.just_project
    #swagger-ui:
    #disable-swagger-default-url: true

app:
  mail-server:
    username: ${MY_APP_MAIL_USER_NAME:}
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN:secret}
      send-msg-post-url: ${TELEGRAM_SEND-MSG-POST-URL:https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s}
      chat:
        id:
          lamardinho: ${LAMARDINHO:367222121}
  rapid-api:
    key: ${RAPIDAPI_KEY:secret}
  football-data-org:
    token: ${FOOTBALL_DATA_ORG_TOKEN:secret}
