spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:sportnotifier}?currentSchema=public
  jpa:
    generate-ddl: false
    open-in-view: false
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.lamardinho.sportnotifier.config.H2IdentifierNamingStrategy
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        globally-quoted-identifiers: true
  liquibase:
    enabled: off
