spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:~/sportnotifier_test_db;MODE=postgresql;DB_CLOSE_DELAY=-1
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.lamardinho.sportnotifier.config.H2IdentifierNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        globally-quoted-identifiers: true
  liquibase:
    enabled: off # WARN !!! if liquibase "on" -> defer-datasource-initialization: false else defer-datasource-initialization: true
  sql:
    init:
      data-locations:

debug: true
